# Generated by Django 3.1.3 on 2021-04-15 13:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin1Code',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (100, 'Enabled'), (500, 'Archived')], default=100)),
                ('geonameid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Admin2Code',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (100, 'Enabled'), (500, 'Archived')], default=100)),
                ('geonameid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('admin1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin2_set', to='geonames.admin1code')),
            ],
            options={
                'ordering': ['country', 'admin1', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (100, 'Enabled'), (500, 'Archived')], default=100)),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (100, 'Enabled'), (500, 'Archived')], default=100)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeonamesUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (100, 'Enabled'), (500, 'Archived')], default=100)),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('iso_639_1', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (100, 'Enabled'), (500, 'Archived')], default=100)),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('gmt_offset', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dst_offset', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ['gmt_offset', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (100, 'Enabled'), (500, 'Archived')], default=100)),
                ('geonameid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('long_name', models.CharField(max_length=200)),
                ('population', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=7)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('modification_date', models.DateField()),
                ('admin1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locality_set', to='geonames.admin1code')),
                ('admin2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locality_set', to='geonames.admin2code')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locality_set', to='geonames.country')),
                ('timezone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locality_set', to='geonames.timezone')),
            ],
            options={
                'verbose_name_plural': 'Localities',
                'ordering': ['country', 'admin1', 'admin2', 'long_name'],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_set', to='geonames.currency'),
        ),
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(related_name='country_set', to='geonames.Language'),
        ),
        migrations.AddField(
            model_name='admin2code',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin2_set', to='geonames.country'),
        ),
        migrations.AddField(
            model_name='admin1code',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin1_set', to='geonames.country'),
        ),
        migrations.CreateModel(
            name='AlternateName',
            fields=[
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (100, 'Enabled'), (500, 'Archived')], default=100)),
                ('alternatenameid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatename_set', to='geonames.locality')),
            ],
            options={
                'ordering': ['locality__pk', 'name'],
                'unique_together': {('locality', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='admin2code',
            unique_together={('country', 'admin1', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='admin1code',
            unique_together={('country', 'name')},
        ),
    ]
