# Generated by Django 2.2.3 on 2019-08-19 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alternatename',
            unique_together=set(),
        ),
    ]
