# Generated by Django 2.2.3 on 2019-08-20 18:27

# import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0002_altnames_remove_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(db_index=True, max_length=20)),
                ('place_name', models.CharField(max_length=180)),
                ('admin_name1', models.CharField(blank=True, max_length=100, null=True, verbose_name='state')),
                ('admin_code1', models.CharField(blank=True, max_length=20, null=True, verbose_name='state')),
                ('admin_name2', models.CharField(blank=True, max_length=100, null=True, verbose_name='county/province')),
                ('admin_code2', models.CharField(blank=True, max_length=20, null=True, verbose_name='county/province')),
                ('admin_name3', models.CharField(blank=True, max_length=100, null=True, verbose_name='community')),
                ('admin_code3', models.CharField(blank=True, max_length=20, null=True, verbose_name='community')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=7)),
                # ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcode_set', to='geonames.Country')),
            ],
        ),
    ]
