# Generated by Django 4.0.1 on 2022-03-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0003_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin2code',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True),
        ),
    ]
