# Generated by Django 3.2 on 2021-09-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0003_postcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locality',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='locality',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='postcode',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='postcode',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.AlterField(
            model_name='locality',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
